/**
 * IMAGE BLUR PLACEHOLDERS FOR NEXT/IMAGE
 * Automatically generated by scripts/optimize-images.mjs
 */

export const IMAGE_BLURS: Record<string, string> = {
  "arac-filosu": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACQAwCdASoUAAsAPzmEuVOvKKWisAgB4CcJZwAARJV8OGSjY0AAAP7IShX7cxUTydxpDkkFcgD9Rmd1jHtHGKdZIezmToTVgt4oFDxdr8ffiUzl0cAAAA==",
  "asansor-kurulum": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAwCdASoUAAsAPzmEuVOvKKWisAgB4CcJZwAARcVf4salw7ALEAAA/taujXs3M22+w9bfvyVnVBmM1BM/6H89Fkt8Jlq6wM7GOQpI5/cmbTgx0CAAAA==",
  "ekip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAACwAwCdASoUAA8APzmEuVOvKKWisAgB4CcJZQAAW3N6Y2WFivCoQAD8q/0fFvuXvcG26ubjapzuv/0+nl5ZmWiyMHyqug0sZKgMRhRtEu24pGKcZfsh91zDkYSA2sLJUpybxhBo6dFXQFN69MiANh7SBzqJUiAA",
  "marangozluk": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACQAwCdASoUAAsAPzmGuVOvKSWisAgB4CcJYgCw7CLc5F8jHJJ4AM4GAHyIMIOEdfWVhXSc/t2yIlHtqVYcEKNYKiQQ2nlzYUv8HZ+oo8+nT8GiKw9vrW0JSN7MWIgAAAA=",
  "paketleme-detay": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAwBACdASoUAA8APzmEuVOvKKWisAgB4CcJQBOmUABr6mZdD4lfe3+6VEAAziTdjMItQbcn5Zh7Qur/asvaUtCVOIjyscMflhVp+BFGw9JZwdEm34l+w0dGHz6WAC8O0wYjFVO5wjlauPou370oiAAA",
  "slayt-1": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABwAwCdASoUAAsAPzmEuVOvKKWisAgB4CcJZwAANrMSjUDL+uAA/rNDkPTDVZYII5ThCt8t0j5CTdfcXACQ2siiJUuzeDDAe9FVuyQ3lcOzFmSFNKuoxT869ggnzS0BBM4LoAAA",
  "slayt-2": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQBACdASoUAAsAPzmGuVOvKSWisAgB4CcJQAqP0Pkxk7ZqiOD9qOMrwAD+bzf19BC3DXNWV+TXdUDZ2IVyOQK9ZEj9DLgJ2skLdZDaPDVYldDywZYyvWdUeqyf4AAA",
  "slayt-3": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADwAwCdASoUAAsAPzmGulOvKKWisAgB4CcJZQCw7BL0f4jOCMFxUvPoAP6e9E93hmQwh8emmPDhHMA/mynZ/3Tr7BeqYW+v8FU9MjkBizN1kHDVZ929Sg1Qy23zLYgAAAA=",
  "banner-bg": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADwAgCdASoUAAsAPzmGuVO0qSWisAgCkCcJZwCAAAunAAD+7VjhrWlzJWYn0OAA"
};
