/**
 * IMAGE BLUR PLACEHOLDERS FOR NEXT/IMAGE
 * Automatically generated by scripts/optimize-images.mjs
 */

export const IMAGE_BLURS: Record<string, string> = {
  "arac-filosu": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACQAwCdASoUAAsAPzmGuVOvKSWisAgB4CcJZwAARJV8OGSjZCWAAP7IShX7cxUTydxpDkkFcgD9Rmd1jHtHGKdZIezmToTVgt4oFVtstuM+ufHAAAA=",
  "asansor-kurulum": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAwCdASoUAAsAPzmGuVOvKSWisAgB4CcJZwAARcViLIvKfXatgAAA/taujXs3M22+w9bfvyVnVBsyh5qC2mW6IaPZBbYR/yVExW4SSopbVArf/YDShAAA",
  "ekip": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAAAQBACdASoUAA8APzmEuVOvKKWisAgB4CcJZQAIEAPUcm7nNejqP8xdIAD8qvtZiVhvBZ4iqQiyBn0Xcmybzruerdq1Zz/1949cTzvgyFk23kKCeTZ4oj7rmHIwkBvfAuL0sYlZ6NJrYyCVgneWjUV/MoFMepMDAAA=",
  "marangozluk": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABwAwCdASoUAAsAPzmGuVOvKSWisAgB4CcJYgCw7CLbaiQYQWAAzgYAfIhF+h+lrqowLY+BMYW2osulu4f6BQmdayIazgQ5OwL8MXi1YR7XXM2fjS33cTP6E5IFnYAA",
  "paketleme-detay": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAwBACdASoUAA8APzmEuVOvKKWisAgB4CcJQBOmUABr6mZdD4lfe3/K1DwAziTdjMItQbcn5Zh7Qur/asvaUtCVOIjyscMflhVp+BFGw9JZwdEm34l+w0dGHz6WAC8O0wYjFVO5wpKjfGCIv/LorQAA",
  "slayt-1": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADQAwCdASoUAAsAPzmGuVOvKSWisAgB4CcJYwCdABDLlGLUq5P56gAA/q8ZctB9ipWbJbYiahWRKWQcAhhu4hAppwH2jdySpOboYWmMhBD2/sKHvgLkOFb+b/K7BN2hnHPuKLEFylmilIZaXmW2HwAA",
  "slayt-2": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQBACdASoUAAsAPzmGuVOvKSWisAgB4CcJQBYfv/wF2sEqN9zjfB9lwAD+BIZirV3Qjxpp/mMUcWdKLn8En/wSj44LVnh1MLRcXZPxRUVS2Tjg/w7dXJNJHSQybf7Fxe8HpoiIOx2Bx72AAAA=",
  "slayt-3": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAACwAwCdASoUAAsAPzmGuVOvKSWisAgB4CcJZgCdAA553wZ2FXUe+AD+xce0xLmyz3PW2jIdBeHyHhAu4nnIQ6ayZmVBsvBJBI+m3mho1XhM+PH6YaM9PHnqGWnycu3/EyfTrNL2sWXXifxwKf4EoTP2/bp0gAAA"
};
